name: Build in CI
run-name: ${{ github.actor }} is running
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build
      run: bazel build //...
    - name: Test
      run: bazel test //...

